### ISSUE TITLE
Akka-stream: source are closed on tailable cursor when using ResponseStage

### ISSUE THREAD

**Issue by vdebergue** [ReactiveMongo/ReactiveMongo-Streaming#29]
### ReactiveMongo Version
0.12.0

### MongoDB version
3.2.10

### Operating System 
MacOS 10.11

### JDK 
Oracle 1.8.0_72

### Library Dependencies
`reactivemongo-akkastream % 0.12.0`

### Expected Behavior

When consuming a capped collection with the `tailable` option and the method `bulkSource`, the source should not be closed. 

### Actual Behavior

The source created using `bulkSource` is closed when there is no more documents to consume. It works fine when using `documentSource`

### Reproducible Test Case

```scala
val sourceBulk: Source[Iterator[String], _] = collection.find(query)
  .options(QueryOpts().tailable)
  .cursor[String]()
  .bulkSource()
// ko: sourceBulk is closed when there is no more documents to consume

val sourceDocs: Source[String, _] = collection.find(query)
  .options(QueryOpts().tailable)
  .cursor[String]()
  .documentSource()
// ok: sourceDocs is not closed
```

There may lack a check to see if the cursor is tailable before completing the stage [here](https://github.com/ReactiveMongo/ReactiveMongo-Streaming/blob/master/akka-stream/src/main/scala/ResponseStage.scala#L93) ?

**Comment by cchantep** [comment]
Will have a look. A [test](https://github.com/ReactiveMongo/ReactiveMongo-Streaming/blob/master/akka-stream/src/test/scala/CursorSpec.scala#L727) must be failing.

**Comment by vdebergue** [comment]
I created a small play app to reproduce the behaviour: https://github.com/vdebergue/reactivemongo-test

- Using `documentSource`, it's ok with chunked and streamed entity:

```bash
% curl -v http://localhost:9000/source
> GET /source HTTP/1.1
> Host: localhost:9000
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: text/plain; charset=utf-8
< Date: Sun, 13 Nov 2016 21:54:58 GMT
<
1
2
3
# // connection stays opened
```

```bash
% curl -v http://localhost:9000/sourceStr
> GET /sourceStr HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Sun, 13 Nov 2016 22:07:32 GMT
< Connection: close
<
1
2
3
# Connection kept opened
```

- Using  `bulkSource` and `Ok.chunked`, connection is closed:
```bash
% curl -v http://localhost:9000/bulk
> GET /bulk HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Transfer-Encoding: chunked
< Content-Type: text/plain; charset=utf-8
< Date: Sun, 13 Nov 2016 22:00:35 GMT
<
* transfer closed with outstanding read data remaining
* Closing connection 0
curl: (18) transfer closed with outstanding read data remaining
```

- Using `bulkSource` and a `HttpEntity.Streamed`, connection is kept opened but nothing is sent:
```
% curl -v http://localhost:9000/stream
*   Trying ::1...
* Connected to localhost (::1) port 9000 (#0)
> GET /stream HTTP/1.1
> Host: localhost:9000
> User-Agent: curl/7.43.0
> Accept: */*
>
< HTTP/1.1 200 OK
< Content-Type: text/plain; charset=utf-8
< Date: Sun, 13 Nov 2016 22:02:09 GMT
< Connection: close
<
// kept opened
```

And in the console, the line `Got 0 ids` keeps getting printed:
```
Got 0 ids
Got 0 ids
...
```

**Comment by cchantep** [comment]
To avoid having an empty chunk (from an empty result bulk) interpreted as `LastChunk`, can you try the following.

```scala
  def tailBulk = Action {
    val source = cursor()
      .bulkSource()
      .map { ids =>
        println(s"Got ${ids.size} ids")
        "X" + ids.mkString("\n")
    }

    Ok.chunked(source)
  }
```

**Comment by vdebergue** [comment]
Seems to be an issue in play framework that doesn't interpret correctly `Seq.empty`
