### ISSUE TITLE
pekko support?

### ISSUE THREAD

**Issue by pjfanning** [ReactiveMongo/ReactiveMongo-Streaming#320]
Would there be any interest in producing a pekko-stream module?

Apache Pekko 1.0.0 has just been released. It is an OSS fork of Akka.

**Comment by cchantep** [comment]
Hi,

Thanks, I will have a look at the PR.

> BTW as indicated in the project guideline/issue template, rather use the [MailingList](https://groups.google.com/g/reactivemongo) for discussion as "this tracker is not a support system and so it is not a place to ask questions or get help".

Best regards
